"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["ul#myTopNavBarMenu[_ngcontent-%COMP%] {\r\n    padding:30px;\r\n  }\r\n\r\n  ul#myTopNavBarMenu[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]{\r\n    display:inline;\r\n    padding:15px 21px 15px 20px;\r\n    border-radius: 5px;\r\n    font-weight:bold;\r\n    color: #1f2c6e;\r\n}\r\n  \r\n  ul#myTopNavBarMenu[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:hover{\r\n    border-bottom: 2px solid #1f2c6e;\r\n    color: red;\r\n  }\r\n\r\n  ul#myTopNavBarMenu[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{\r\n    font-weight:bold;\r\n    color: black;\r\n  }\r\n\r\n  ul#myTopNavBarMenu[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover{\r\n    text-decoration: none;\r\n    color: white;\r\n  }"];
exports.styles = styles;
//# sourceMappingURL=header.component.scss.shim.ngstyle.js.map